TEST_SIMULATORS = ['iPhone 11 Pro Max']
SCHEME = "SBrain"

default_platform(:ios)

before_all do
  cocoapods(repo_update: true)
end

desc "Runs all the tests"
lane :test do
  scan(
    workspace:"SBrain.xcworkspace",
    scheme: "SBrain"
  )
  xcov(
    workspace: "SBrain.xcworkspace",
    scheme: "SBrain",
    minimum_coverage_percentage: 60.0,
    output_directory: "xcov_output"
  )
end
desc "Submit a new Beta Build to Apple TestFlight"
desc "This will also make sure the profile is up to date"
lane :beta do
  # match(type: "appstore") # more information: https://codesigning.guide
  gym # Build your app - more options available
  pilot

  # sh "your_script.sh"
  # You can also use other beta testing services here (run `fastlane actions`)
end

desc "Deploy a new version to the App Store"
lane :release do
  # match(type: "appstore")
  # snapshot
  gym # Build your app - more options available
  deliver(force: true)
  # frameit
end


