name: CI

on:
  push:
    branches:
      - fix/*
      - feature/*
  pull_request:
    branches:
      - master
jobs:
  Test:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install bundler dependencies
      run: bundler install
    - name: Install pod dependencies
      run: bundler exec pod install
    - name: Run fastlane test
      run: bundler exec fastlane test
